# Site settings
title: Ragsdale Lab at UW--Madison
header-img: img/Banner0.jpg
email: apragsdale@wisc.edu
description: "Ragsdale Lab website"
baseurl: ""
url: "http://apragsdale.github.io"
twitter_username: apragsdale
github_username:  apragsdale

# Google Analytics
google_tracking_id: UA-25895598-2

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
